"""
select {([Measures].[Customer Count]), ([Measures].[Sales Count])} 
               * {([Time].[1997].[Q2].[4]), ([Time].[1997].[Q2].[5]) } on columns, 
        [Gender].[Gender].ALLMEMBERS on rows 
        from [Sales]

"""

result={'Axes': {'Axis': [{'Tuples': {'Tuple': [{'Member': [{'Caption': 'Customer '
                                                                 'Count',
                                                      'DisplayInfo': '0',
                                                      'LName': '[Measures].[MeasuresLevel]',
                                                      'LNum': '0',
                                                      'UName': '[Measures].[Customer '
                                                               'Count]',
                                                      '_Hierarchy': 'Measures'},
                                                     {'Caption': '4',
                                                      'DisplayInfo': '0',
                                                      'LName': '[Time].[Month]',
                                                      'LNum': '2',
                                                      'UName': '[Time].[1997].[Q2].[4]',
                                                      '_Hierarchy': 'Time'}]},
                                         {'Member': [{'Caption': 'Customer '
                                                                 'Count',
                                                      'DisplayInfo': '0',
                                                      'LName': '[Measures].[MeasuresLevel]',
                                                      'LNum': '0',
                                                      'UName': '[Measures].[Customer '
                                                               'Count]',
                                                      '_Hierarchy': 'Measures'},
                                                     {'Caption': '5',
                                                      'DisplayInfo': '131072',
                                                      'LName': '[Time].[Month]',
                                                      'LNum': '2',
                                                      'UName': '[Time].[1997].[Q2].[5]',
                                                      '_Hierarchy': 'Time'}]},
                                         {'Member': [{'Caption': 'Sales Count',
                                                      'DisplayInfo': '0',
                                                      'LName': '[Measures].[MeasuresLevel]',
                                                      'LNum': '0',
                                                      'UName': '[Measures].[Sales '
                                                               'Count]',
                                                      '_Hierarchy': 'Measures'},
                                                     {'Caption': '4',
                                                      'DisplayInfo': '131072',
                                                      'LName': '[Time].[Month]',
                                                      'LNum': '2',
                                                      'UName': '[Time].[1997].[Q2].[4]',
                                                      '_Hierarchy': 'Time'}]},
                                         {'Member': [{'Caption': 'Sales Count',
                                                      'DisplayInfo': '0',
                                                      'LName': '[Measures].[MeasuresLevel]',
                                                      'LNum': '0',
                                                      'UName': '[Measures].[Sales '
                                                               'Count]',
                                                      '_Hierarchy': 'Measures'},
                                                     {'Caption': '5',
                                                      'DisplayInfo': '131072',
                                                      'LName': '[Time].[Month]',
                                                      'LNum': '2',
                                                      'UName': '[Time].[1997].[Q2].[5]',
                                                      '_Hierarchy': 'Time'}]}]},
                    '_name': 'Axis0'},
                   {'Tuples': {'Tuple': [{'Member': {'Caption': 'F',
                                                     'DisplayInfo': '0',
                                                     'LName': '[Gender].[Gender]',
                                                     'LNum': '1',
                                                     'UName': '[Gender].[F]',
                                                     '_Hierarchy': 'Gender'}},
                                         {'Member': {'Caption': 'M',
                                                     'DisplayInfo': '131072',
                                                     'LName': '[Gender].[Gender]',
                                                     'LNum': '1',
                                                     'UName': '[Gender].[M]',
                                                     '_Hierarchy': 'Gender'}}]},
                    '_name': 'Axis1'},
                   {'Tuples': {'Tuple': None}, '_name': 'SlicerAxis'}]},
 'CellData': {'Cell': [{'FmtValue': '657',
                        'FormatString': '#,###',
                        'Value': 657,
                        '_CellOrdinal': '0'},
                       {'FmtValue': '672',
                        'FormatString': '#,###',
                        'Value': 672,
                        '_CellOrdinal': '1'},
                       {'FmtValue': '3.251',
                        'FormatString': '#,###',
                        'Value': 3251,
                        '_CellOrdinal': '2'},
                       {'FmtValue': '3.438',
                        'FormatString': '#,###',
                        'Value': 3438,
                        '_CellOrdinal': '3'},
                       {'FmtValue': '660',
                        'FormatString': '#,###',
                        'Value': 660,
                        '_CellOrdinal': '4'},
                       {'FmtValue': '699',
                        'FormatString': '#,###',
                        'Value': 699,
                        '_CellOrdinal': '5'},
                       {'FmtValue': '3.339',
                        'FormatString': '#,###',
                        'Value': 3339,
                        '_CellOrdinal': '6'},
                       {'FmtValue': '3.428',
                        'FormatString': '#,###',
                        'Value': 3428,
                        '_CellOrdinal': '7'}]},
 'OlapInfo': {'AxesInfo': {'AxisInfo': [{'HierarchyInfo': [{'Caption': {'_name': '[Measures].[MEMBER_CAPTION]'},
                                                            'DisplayInfo': {'_name': '[Measures].[DISPLAY_INFO]'},
                                                            'LName': {'_name': '[Measures].[LEVEL_UNIQUE_NAME]'},
                                                            'LNum': {'_name': '[Measures].[LEVEL_NUMBER]'},
                                                            'UName': {'_name': '[Measures].[MEMBER_UNIQUE_NAME]'},
                                                            '_name': 'Measures'},
                                                           {'Caption': {'_name': '[Time].[MEMBER_CAPTION]'},
                                                            'DisplayInfo': {'_name': '[Time].[DISPLAY_INFO]'},
                                                            'LName': {'_name': '[Time].[LEVEL_UNIQUE_NAME]'},
                                                            'LNum': {'_name': '[Time].[LEVEL_NUMBER]'},
                                                            'UName': {'_name': '[Time].[MEMBER_UNIQUE_NAME]'},
                                                            '_name': 'Time'}],
                                         '_name': 'Axis0'},
                                        {'HierarchyInfo': {'Caption': {'_name': '[Gender].[MEMBER_CAPTION]'},
                                                           'DisplayInfo': {'_name': '[Gender].[DISPLAY_INFO]'},
                                                           'LName': {'_name': '[Gender].[LEVEL_UNIQUE_NAME]'},
                                                           'LNum': {'_name': '[Gender].[LEVEL_NUMBER]'},
                                                           'UName': {'_name': '[Gender].[MEMBER_UNIQUE_NAME]'},
                                                           '_name': 'Gender'},
                                         '_name': 'Axis1'},
                                        {'_name': 'SlicerAxis'}]},
              'CellInfo': {'FmtValue': {'_name': 'FORMATTED_VALUE'},
                           'FormatString': {'_name': 'FORMAT_STRING'},
                           'Value': {'_name': 'VALUE'}},
              'CubeInfo': {'Cube': {'CubeName': 'Sales'}}}}
