"""
select {} on columns,
      [Geschlecht].[Geschlecht].[Level 01].ALLMEMBERS on rows
from [fused]

"""

result={'Axes': {'Axis': [{'Tuples': '', '_name': 'Axis0'},
                   {'Tuples': {'Tuple': [{'Member': {'Caption': 'weiblich',
                                                     'DisplayInfo': '0',
                                                     'LName': '[Geschlecht].[Geschlecht].[Level 01]',
                                                     'LNum': '1',
                                                     'UName': '[Geschlecht].[Geschlecht].[weiblich]',
                                                     '_Hierarchy': '[Geschlecht].[Geschlecht]'}},
                                         {'Member': {'Caption': 'm\xe4nnlich',
                                                     'DisplayInfo': '131072',
                                                     'LName': '[Geschlecht].[Geschlecht].[Level 01]',
                                                     'LNum': '1',
                                                     'UName': '[Geschlecht].[Geschlecht].[m\xe4nnlich]',
                                                     '_Hierarchy': '[Geschlecht].[Geschlecht]'}}]},
                    '_name': 'Axis1'},
                   {'Tuples': {'Tuple': {'Member': [{'Caption': 'Mitarbeiteranzahl',
                                                     'DisplayInfo': '0',
                                                     'LName': '[Measures].[MeasuresLevel]',
                                                     'LNum': '0',
                                                     'UName': '[Measures].[Mitarbeiteranzahl]',
                                                     '_Hierarchy': '[Measures]'},
                                                    {'Caption': 'Alle',
                                                     'DisplayInfo': '10',
                                                     'LName': '[Zeit].[Monate].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Zeit].[Monate].[Alle]',
                                                     '_Hierarchy': '[Zeit].[Monate]'},
                                                    {'Caption': 'Zeit Gesamt',
                                                     'DisplayInfo': '10',
                                                     'LName': '[Zeit].[Zeit].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Zeit].[Zeit].[Zeit Gesamt]',
                                                     '_Hierarchy': '[Zeit].[Zeit]'},
                                                    {'Caption': 'Alle Vertragsbefristungen',
                                                     'DisplayInfo': '2',
                                                     'LName': '[Vertragsbefristung].[Vertragsbefristung].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Vertragsbefristung].[Vertragsbefristung].[Alle Vertragsbefristungen]',
                                                     '_Hierarchy': '[Vertragsbefristung].[Vertragsbefristung]'},
                                                    {'Caption': 'Alle Mitarbeitergruppen',
                                                     'DisplayInfo': '5',
                                                     'LName': '[Mitarbeitergruppe].[Mitarbeitergruppe].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Mitarbeitergruppe].[Mitarbeitergruppe].[Alle Mitarbeitergruppen]',
                                                     '_Hierarchy': '[Mitarbeitergruppe].[Mitarbeitergruppe]'},
                                                    {'Caption': 'Alle',
                                                     'DisplayInfo': '7',
                                                     'LName': '[Funktionsbezeichnung].[Funktionsbezeichnung].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Funktionsbezeichnung].[Funktionsbezeichnung].[Alle]',
                                                     '_Hierarchy': '[Funktionsbezeichnung].[Funktionsbezeichnung]'},
                                                    {'Caption': 'jedes Alter',
                                                     'DisplayInfo': '9',
                                                     'LName': '[Alter].[Alter].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Alter].[Alter].[jedes Alter]',
                                                     '_Hierarchy': '[Alter].[Alter]'},
                                                    {'Caption': 'Alle Vertragsarten',
                                                     'DisplayInfo': '46',
                                                     'LName': '[Vertragsart].[Vertragsart].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Vertragsart].[Vertragsart].[Alle Vertragsarten]',
                                                     '_Hierarchy': '[Vertragsart].[Vertragsart]'},
                                                    {'Caption': 'Alle Betriebszugeh\xf6rigkeiten',
                                                     'DisplayInfo': '10',
                                                     'LName': '[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[Alle Betriebszugeh\xf6rigkeiten]',
                                                     '_Hierarchy': '[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit]'},
                                                    {'Caption': 'Alle Standorte',
                                                     'DisplayInfo': '3',
                                                     'LName': '[Standort].[Standort].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Standort].[Standort].[Alle Standorte]',
                                                     '_Hierarchy': '[Standort].[Standort]'},
                                                    {'Caption': 'AP',
                                                     'DisplayInfo': '0',
                                                     'LName': '[Zeitbetrachtung].[Zeitbetrachtung].[Zeitbetrachtung]',
                                                     'LNum': '0',
                                                     'UName': '[Zeitbetrachtung].[Zeitbetrachtung].[AP]',
                                                     '_Hierarchy': '[Zeitbetrachtung].[Zeitbetrachtung]'},
                                                    {'Caption': 'Kieback&Peter GmbH & Co.KG',
                                                     'DisplayInfo': '6',
                                                     'LName': '[Kostenstelle].[Kostenstelle].[Level 01]',
                                                     'LNum': '0',
                                                     'UName': '[Kostenstelle].[Kostenstelle].[Kieback&Peter GmbH & Co.KG]',
                                                     '_Hierarchy': '[Kostenstelle].[Kostenstelle]'},
                                                    {'Caption': 'All',
                                                     'DisplayInfo': '1883',
                                                     'LName': '[Kostenstelle].[PNR].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Kostenstelle].[PNR].[All]',
                                                     '_Hierarchy': '[Kostenstelle].[PNR]'},
                                                    {'Caption': 'All',
                                                     'DisplayInfo': '385',
                                                     'LName': '[Kostenstelle].[Eintritt].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Kostenstelle].[Eintritt].[All]',
                                                     '_Hierarchy': '[Kostenstelle].[Eintritt]'},
                                                    {'Caption': 'All',
                                                     'DisplayInfo': '385',
                                                     'LName': '[Kostenstelle].[Eintritt2].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Kostenstelle].[Eintritt2].[All]',
                                                     '_Hierarchy': '[Kostenstelle].[Eintritt2]'},
                                                    {'Caption': 'KST Gesamt',
                                                     'DisplayInfo': '720',
                                                     'LName': '[KST].[KST].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[KST].[KST].[KST Gesamt]',
                                                     '_Hierarchy': '[KST].[KST]'},
                                                    {'Caption': 'All',
                                                     'DisplayInfo': '1883',
                                                     'LName': '[Person].[Person].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Person].[Person].[All]',
                                                     '_Hierarchy': '[Person].[Person]'},
                                                    {'Caption': 'Alle Personen',
                                                     'DisplayInfo': '178',
                                                     'LName': '[Person].[Person Austritt].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Person].[Person Austritt].[Alle Personen]',
                                                     '_Hierarchy': '[Person].[Person Austritt]'},
                                                    {'Caption': 'Alle Personen',
                                                     'DisplayInfo': '3',
                                                     'LName': '[Person].[Person aktiv].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Person].[Person aktiv].[Alle Personen]',
                                                     '_Hierarchy': '[Person].[Person aktiv]'},
                                                    {'Caption': 'Alle Kostenarten',
                                                     'DisplayInfo': '5',
                                                     'LName': '[Kostenart].[Kostenart].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Kostenart].[Kostenart].[Alle Kostenarten]',
                                                     '_Hierarchy': '[Kostenart].[Kostenart]'},
                                                    {'Caption': 'Alle Kostenarten',
                                                     'DisplayInfo': '40',
                                                     'LName': '[Kostenart].[Level 02 Bezeichnung].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[Kostenart].[Level 02 Bezeichnung].[Alle Kostenarten]',
                                                     '_Hierarchy': '[Kostenart].[Level 02 Bezeichnung]'},
                                                    {'Caption': 'All',
                                                     'DisplayInfo': '2',
                                                     'LName': '[UserAccount].[UserAccount].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[UserAccount].[UserAccount].[All]',
                                                     '_Hierarchy': '[UserAccount].[UserAccount]'},
                                                    {'Caption': 'All',
                                                     'DisplayInfo': '1',
                                                     'LName': '[UserAccount].[Level 01 username].[(All)]',
                                                     'LNum': '0',
                                                     'UName': '[UserAccount].[Level 01 username].[All]',
                                                     '_Hierarchy': '[UserAccount].[Level 01 username]'}]}},
                    '_name': 'SlicerAxis'}]},
 'CellData': '',
 'OlapInfo': {'AxesInfo': {'AxisInfo': [{'_name': 'Axis0'},
                                        {'HierarchyInfo': {'Caption': {'_name': '[Geschlecht].[Geschlecht].[MEMBER_CAPTION]',
                                                                       '_type': 'xsd:string'},
                                                           'DisplayInfo': {'_name': '[Geschlecht].[Geschlecht].[DISPLAY_INFO]',
                                                                           '_type': 'xsd:unsignedInt'},
                                                           'LName': {'_name': '[Geschlecht].[Geschlecht].[LEVEL_UNIQUE_NAME]',
                                                                     '_type': 'xsd:string'},
                                                           'LNum': {'_name': '[Geschlecht].[Geschlecht].[LEVEL_NUMBER]',
                                                                    '_type': 'xsd:int'},
                                                           'UName': {'_name': '[Geschlecht].[Geschlecht].[MEMBER_UNIQUE_NAME]',
                                                                     '_type': 'xsd:string'},
                                                           '_name': '[Geschlecht].[Geschlecht]'},
                                         '_name': 'Axis1'},
                                        {'HierarchyInfo': [{'Caption': {'_name': '[Measures].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Measures].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Measures].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Measures].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Measures].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Measures]'},
                                                           {'Caption': {'_name': '[Zeit].[Monate].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Zeit].[Monate].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Zeit].[Monate].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Zeit].[Monate].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Zeit].[Monate].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Zeit].[Monate]'},
                                                           {'Caption': {'_name': '[Zeit].[Zeit].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Zeit].[Zeit].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Zeit].[Zeit].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Zeit].[Zeit].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Zeit].[Zeit].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Zeit].[Zeit]'},
                                                           {'Caption': {'_name': '[Vertragsbefristung].[Vertragsbefristung].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Vertragsbefristung].[Vertragsbefristung].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Vertragsbefristung].[Vertragsbefristung].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Vertragsbefristung].[Vertragsbefristung].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Vertragsbefristung].[Vertragsbefristung].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Vertragsbefristung].[Vertragsbefristung]'},
                                                           {'Caption': {'_name': '[Mitarbeitergruppe].[Mitarbeitergruppe].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Mitarbeitergruppe].[Mitarbeitergruppe].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Mitarbeitergruppe].[Mitarbeitergruppe].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Mitarbeitergruppe].[Mitarbeitergruppe].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Mitarbeitergruppe].[Mitarbeitergruppe].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Mitarbeitergruppe].[Mitarbeitergruppe]'},
                                                           {'Caption': {'_name': '[Funktionsbezeichnung].[Funktionsbezeichnung].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Funktionsbezeichnung].[Funktionsbezeichnung].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Funktionsbezeichnung].[Funktionsbezeichnung].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Funktionsbezeichnung].[Funktionsbezeichnung].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Funktionsbezeichnung].[Funktionsbezeichnung].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Funktionsbezeichnung].[Funktionsbezeichnung]'},
                                                           {'Caption': {'_name': '[Alter].[Alter].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Alter].[Alter].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Alter].[Alter].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Alter].[Alter].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Alter].[Alter].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Alter].[Alter]'},
                                                           {'Caption': {'_name': '[Vertragsart].[Vertragsart].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Vertragsart].[Vertragsart].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Vertragsart].[Vertragsart].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Vertragsart].[Vertragsart].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Vertragsart].[Vertragsart].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Vertragsart].[Vertragsart]'},
                                                           {'Caption': {'_name': '[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit]'},
                                                           {'Caption': {'_name': '[Standort].[Standort].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Standort].[Standort].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Standort].[Standort].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Standort].[Standort].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Standort].[Standort].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Standort].[Standort]'},
                                                           {'Caption': {'_name': '[Zeitbetrachtung].[Zeitbetrachtung].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Zeitbetrachtung].[Zeitbetrachtung].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Zeitbetrachtung].[Zeitbetrachtung].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Zeitbetrachtung].[Zeitbetrachtung].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Zeitbetrachtung].[Zeitbetrachtung].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Zeitbetrachtung].[Zeitbetrachtung]'},
                                                           {'Caption': {'_name': '[Kostenstelle].[Kostenstelle].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Kostenstelle].[Kostenstelle].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Kostenstelle].[Kostenstelle].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Kostenstelle].[Kostenstelle].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Kostenstelle].[Kostenstelle].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Kostenstelle].[Kostenstelle]'},
                                                           {'Caption': {'_name': '[Kostenstelle].[PNR].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Kostenstelle].[PNR].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Kostenstelle].[PNR].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Kostenstelle].[PNR].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Kostenstelle].[PNR].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Kostenstelle].[PNR]'},
                                                           {'Caption': {'_name': '[Kostenstelle].[Eintritt].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Kostenstelle].[Eintritt].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Kostenstelle].[Eintritt].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Kostenstelle].[Eintritt].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Kostenstelle].[Eintritt].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Kostenstelle].[Eintritt]'},
                                                           {'Caption': {'_name': '[Kostenstelle].[Eintritt2].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Kostenstelle].[Eintritt2].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Kostenstelle].[Eintritt2].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Kostenstelle].[Eintritt2].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Kostenstelle].[Eintritt2].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Kostenstelle].[Eintritt2]'},
                                                           {'Caption': {'_name': '[KST].[KST].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[KST].[KST].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[KST].[KST].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[KST].[KST].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[KST].[KST].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[KST].[KST]'},
                                                           {'Caption': {'_name': '[Person].[Person].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Person].[Person].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Person].[Person].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Person].[Person].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Person].[Person].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Person].[Person]'},
                                                           {'Caption': {'_name': '[Person].[Person Austritt].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Person].[Person Austritt].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Person].[Person Austritt].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Person].[Person Austritt].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Person].[Person Austritt].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Person].[Person Austritt]'},
                                                           {'Caption': {'_name': '[Person].[Person aktiv].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Person].[Person aktiv].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Person].[Person aktiv].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Person].[Person aktiv].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Person].[Person aktiv].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Person].[Person aktiv]'},
                                                           {'Caption': {'_name': '[Kostenart].[Kostenart].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Kostenart].[Kostenart].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Kostenart].[Kostenart].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Kostenart].[Kostenart].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Kostenart].[Kostenart].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Kostenart].[Kostenart]'},
                                                           {'Caption': {'_name': '[Kostenart].[Level 02 Bezeichnung].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[Kostenart].[Level 02 Bezeichnung].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[Kostenart].[Level 02 Bezeichnung].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[Kostenart].[Level 02 Bezeichnung].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[Kostenart].[Level 02 Bezeichnung].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[Kostenart].[Level 02 Bezeichnung]'},
                                                           {'Caption': {'_name': '[UserAccount].[UserAccount].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[UserAccount].[UserAccount].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[UserAccount].[UserAccount].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[UserAccount].[UserAccount].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[UserAccount].[UserAccount].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[UserAccount].[UserAccount]'},
                                                           {'Caption': {'_name': '[UserAccount].[Level 01 username].[MEMBER_CAPTION]',
                                                                        '_type': 'xsd:string'},
                                                            'DisplayInfo': {'_name': '[UserAccount].[Level 01 username].[DISPLAY_INFO]',
                                                                            '_type': 'xsd:unsignedInt'},
                                                            'LName': {'_name': '[UserAccount].[Level 01 username].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            'LNum': {'_name': '[UserAccount].[Level 01 username].[LEVEL_NUMBER]',
                                                                     '_type': 'xsd:int'},
                                                            'UName': {'_name': '[UserAccount].[Level 01 username].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': 'xsd:string'},
                                                            '_name': '[UserAccount].[Level 01 username]'}],
                                         '_name': 'SlicerAxis'}]},
              'CellInfo': {'CellOrdinal': {'_name': 'CELL_ORDINAL',
                                           '_type': 'xsd:unsignedInt'},
                           'FmtValue': {'_name': 'FORMATTED_VALUE',
                                        '_type': 'xsd:string'},
                           'Value': {'_name': 'VALUE'}},
              'CubeInfo': {'Cube': {'CubeName': 'fused',
                                    'LastDataUpdate': '2012-11-16T07:47:31.283333',
                                    'LastSchemaUpdate': '2012-11-16T07:47:28.106667'}}},
 'schema': {'_elementFormDefault': 'qualified',
            '_targetNamespace': 'urn:schemas-microsoft-com:xml-analysis:mddataset',
            'complexType': [{'_name': 'MemberType',
                             'attribute': {'_name': 'Hierarchy',
                                           '_type': 'xs:string'},
                             'sequence': {'any': {'_maxOccurs': 'unbounded',
                                                  '_minOccurs': '0',
                                                  '_namespace': '##targetNamespace',
                                                  '_processContents': 'skip'}}},
                            {'_name': 'PropType',
                             'attribute': [{'_name': 'name',
                                            '_type': 'xs:string',
                                            '_use': 'required'},
                                           {'_name': 'type',
                                            '_type': 'xs:QName'}],
                             'sequence': {'element': {'_minOccurs': '0',
                                                      '_name': 'Default'}}},
                            {'_name': 'TupleType',
                             'sequence': {'element': {'_maxOccurs': 'unbounded',
                                                      '_minOccurs': '0',
                                                      '_name': 'Member',
                                                      '_type': 'MemberType'}}},
                            {'_name': 'MembersType',
                             'attribute': {'_name': 'Hierarchy',
                                           '_type': 'xs:string',
                                           '_use': 'required'},
                             'sequence': {'element': {'_maxOccurs': 'unbounded',
                                                      '_minOccurs': '0',
                                                      '_name': 'Member',
                                                      '_type': 'MemberType'}}},
                            {'_name': 'TuplesType',
                             'sequence': {'element': {'_maxOccurs': 'unbounded',
                                                      '_minOccurs': '0',
                                                      '_name': 'Tuple',
                                                      '_type': 'TupleType'}}},
                            {'_name': 'SetListType',
                             'attribute': {'_name': 'Size',
                                           '_type': 'xs:unsignedInt'},
                             'group': {'_maxOccurs': 'unbounded',
                                       '_minOccurs': '0',
                                       '_ref': 'SetType'}},
                            {'_name': 'OlapInfo',
                             'sequence': {'element': [{'_name': 'CubeInfo',
                                                       'complexType': {'sequence': {'element': {'_maxOccurs': 'unbounded',
                                                                                                '_name': 'Cube',
                                                                                                'complexType': {'sequence': {'element': [{'_name': 'CubeName',
                                                                                                                                          '_type': 'xs:string'},
                                                                                                                                         {'_minOccurs': '0',
                                                                                                                                          '_name': 'LastDataUpdate',
                                                                                                                                          '_type': 'xs:dateTime'},
                                                                                                                                         {'_minOccurs': '0',
                                                                                                                                          '_name': 'LastSchemaUpdate',
                                                                                                                                          '_type': 'xs:dateTime'}]}}}}}},
                                                      {'_name': 'AxesInfo',
                                                       'complexType': {'sequence': {'element': {'_maxOccurs': 'unbounded',
                                                                                                '_name': 'AxisInfo',
                                                                                                'complexType': {'attribute': {'_name': 'name',
                                                                                                                              '_type': 'xs:string'},
                                                                                                                'sequence': {'element': {'_maxOccurs': 'unbounded',
                                                                                                                                         '_minOccurs': '0',
                                                                                                                                         '_name': 'HierarchyInfo',
                                                                                                                                         'complexType': {'attribute': {'_name': 'name',
                                                                                                                                                                       '_type': 'xs:string',
                                                                                                                                                                       '_use': 'required'},
                                                                                                                                                         'sequence': {'any': {'_maxOccurs': 'unbounded',
                                                                                                                                                                              '_minOccurs': '0',
                                                                                                                                                                              '_namespace': '##targetNamespace',
                                                                                                                                                                              '_processContents': 'skip'}}}}}}}}}},
                                                      {'_name': 'CellInfo',
                                                       'complexType': {'choice': {'_maxOccurs': 'unbounded',
                                                                                  '_minOccurs': '0',
                                                                                  'any': {'_maxOccurs': 'unbounded',
                                                                                          '_minOccurs': '0',
                                                                                          '_namespace': '##targetNamespace',
                                                                                          '_processContents': 'skip'}}}}]}},
                            {'_name': 'Axes',
                             'sequence': {'element': {'_maxOccurs': 'unbounded',
                                                      '_name': 'Axis',
                                                      'complexType': {'attribute': {'_name': 'name',
                                                                                    '_type': 'xs:string'},
                                                                      'group': {'_maxOccurs': 'unbounded',
                                                                                '_minOccurs': '0',
                                                                                '_ref': 'SetType'}}}}},
                            {'_name': 'CellData',
                             'sequence': {'element': {'_maxOccurs': 'unbounded',
                                                      '_minOccurs': '0',
                                                      '_name': 'Cell',
                                                      'complexType': {'attribute': {'_name': 'CellOrdinal',
                                                                                    '_type': 'xs:unsignedInt',
                                                                                    '_use': 'required'},
                                                                      'sequence': {'any': {'_maxOccurs': 'unbounded',
                                                                                           '_minOccurs': '0',
                                                                                           '_namespace': '##targetNamespace',
                                                                                           '_processContents': 'skip'}}}}}}],
            'element': {'_name': 'root',
                        'complexType': {'sequence': {'any': {'_minOccurs': '0',
                                                             '_namespace': 'http://www.w3.org/2001/XMLSchema',
                                                             '_processContents': 'strict'},
                                                     'element': [{'_minOccurs': '0',
                                                                  '_name': 'OlapInfo',
                                                                  '_type': 'OlapInfo'},
                                                                 {'_minOccurs': '0',
                                                                  '_name': 'Axes',
                                                                  '_type': 'Axes'},
                                                                 {'_minOccurs': '0',
                                                                  '_name': 'CellData',
                                                                  '_type': 'CellData'}]}}},
            'group': {'_name': 'SetType',
                      'choice': {'element': [{'_name': 'Members',
                                              '_type': 'MembersType'},
                                             {'_name': 'Tuples',
                                              '_type': 'TuplesType'},
                                             {'_name': 'CrossProduct',
                                              '_type': 'SetListType'},
                                             {'_ref': 'msxmla:NormTupleSet'},
                                             {'_name': 'Union',
                                              'complexType': {'group': {'_maxOccurs': 'unbounded',
                                                                        '_minOccurs': '0',
                                                                        '_ref': 'SetType'}}}]}},
            'import': {'_namespace': 'http://schemas.microsoft.com/analysisservices/2003/xmla'}}}

