"""
select {} on columns,
      [Geschlecht].[Geschlecht].[Level 01].ALLMEMBERS on rows
from [fused]

"""

result={'Axes': {'Axis': [{'Tuples': u'', '_name': u'Axis0'},
                   {'Tuples': {'Tuple': [{'Member': {'Caption': u'weiblich',
                                                     'DisplayInfo': u'0',
                                                     'LName': u'[Geschlecht].[Geschlecht].[Level 01]',
                                                     'LNum': u'1',
                                                     'UName': u'[Geschlecht].[Geschlecht].[weiblich]',
                                                     '_Hierarchy': u'[Geschlecht].[Geschlecht]'}},
                                         {'Member': {'Caption': u'm\xe4nnlich',
                                                     'DisplayInfo': u'131072',
                                                     'LName': u'[Geschlecht].[Geschlecht].[Level 01]',
                                                     'LNum': u'1',
                                                     'UName': u'[Geschlecht].[Geschlecht].[m\xe4nnlich]',
                                                     '_Hierarchy': u'[Geschlecht].[Geschlecht]'}}]},
                    '_name': u'Axis1'},
                   {'Tuples': {'Tuple': {'Member': [{'Caption': u'Mitarbeiteranzahl',
                                                     'DisplayInfo': u'0',
                                                     'LName': u'[Measures].[MeasuresLevel]',
                                                     'LNum': u'0',
                                                     'UName': u'[Measures].[Mitarbeiteranzahl]',
                                                     '_Hierarchy': u'[Measures]'},
                                                    {'Caption': u'Alle',
                                                     'DisplayInfo': u'10',
                                                     'LName': u'[Zeit].[Monate].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Zeit].[Monate].[Alle]',
                                                     '_Hierarchy': u'[Zeit].[Monate]'},
                                                    {'Caption': u'Zeit Gesamt',
                                                     'DisplayInfo': u'10',
                                                     'LName': u'[Zeit].[Zeit].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Zeit].[Zeit].[Zeit Gesamt]',
                                                     '_Hierarchy': u'[Zeit].[Zeit]'},
                                                    {'Caption': u'Alle Vertragsbefristungen',
                                                     'DisplayInfo': u'2',
                                                     'LName': u'[Vertragsbefristung].[Vertragsbefristung].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Vertragsbefristung].[Vertragsbefristung].[Alle Vertragsbefristungen]',
                                                     '_Hierarchy': u'[Vertragsbefristung].[Vertragsbefristung]'},
                                                    {'Caption': u'Alle Mitarbeitergruppen',
                                                     'DisplayInfo': u'5',
                                                     'LName': u'[Mitarbeitergruppe].[Mitarbeitergruppe].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Mitarbeitergruppe].[Mitarbeitergruppe].[Alle Mitarbeitergruppen]',
                                                     '_Hierarchy': u'[Mitarbeitergruppe].[Mitarbeitergruppe]'},
                                                    {'Caption': u'Alle',
                                                     'DisplayInfo': u'7',
                                                     'LName': u'[Funktionsbezeichnung].[Funktionsbezeichnung].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Funktionsbezeichnung].[Funktionsbezeichnung].[Alle]',
                                                     '_Hierarchy': u'[Funktionsbezeichnung].[Funktionsbezeichnung]'},
                                                    {'Caption': u'jedes Alter',
                                                     'DisplayInfo': u'9',
                                                     'LName': u'[Alter].[Alter].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Alter].[Alter].[jedes Alter]',
                                                     '_Hierarchy': u'[Alter].[Alter]'},
                                                    {'Caption': u'Alle Vertragsarten',
                                                     'DisplayInfo': u'46',
                                                     'LName': u'[Vertragsart].[Vertragsart].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Vertragsart].[Vertragsart].[Alle Vertragsarten]',
                                                     '_Hierarchy': u'[Vertragsart].[Vertragsart]'},
                                                    {'Caption': u'Alle Betriebszugeh\xf6rigkeiten',
                                                     'DisplayInfo': u'10',
                                                     'LName': u'[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[Alle Betriebszugeh\xf6rigkeiten]',
                                                     '_Hierarchy': u'[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit]'},
                                                    {'Caption': u'Alle Standorte',
                                                     'DisplayInfo': u'3',
                                                     'LName': u'[Standort].[Standort].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Standort].[Standort].[Alle Standorte]',
                                                     '_Hierarchy': u'[Standort].[Standort]'},
                                                    {'Caption': u'AP',
                                                     'DisplayInfo': u'0',
                                                     'LName': u'[Zeitbetrachtung].[Zeitbetrachtung].[Zeitbetrachtung]',
                                                     'LNum': u'0',
                                                     'UName': u'[Zeitbetrachtung].[Zeitbetrachtung].[AP]',
                                                     '_Hierarchy': u'[Zeitbetrachtung].[Zeitbetrachtung]'},
                                                    {'Caption': u'Kieback&Peter GmbH & Co.KG',
                                                     'DisplayInfo': u'6',
                                                     'LName': u'[Kostenstelle].[Kostenstelle].[Level 01]',
                                                     'LNum': u'0',
                                                     'UName': u'[Kostenstelle].[Kostenstelle].[Kieback&Peter GmbH & Co.KG]',
                                                     '_Hierarchy': u'[Kostenstelle].[Kostenstelle]'},
                                                    {'Caption': u'All',
                                                     'DisplayInfo': u'1883',
                                                     'LName': u'[Kostenstelle].[PNR].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Kostenstelle].[PNR].[All]',
                                                     '_Hierarchy': u'[Kostenstelle].[PNR]'},
                                                    {'Caption': u'All',
                                                     'DisplayInfo': u'385',
                                                     'LName': u'[Kostenstelle].[Eintritt].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Kostenstelle].[Eintritt].[All]',
                                                     '_Hierarchy': u'[Kostenstelle].[Eintritt]'},
                                                    {'Caption': u'All',
                                                     'DisplayInfo': u'385',
                                                     'LName': u'[Kostenstelle].[Eintritt2].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Kostenstelle].[Eintritt2].[All]',
                                                     '_Hierarchy': u'[Kostenstelle].[Eintritt2]'},
                                                    {'Caption': u'KST Gesamt',
                                                     'DisplayInfo': u'720',
                                                     'LName': u'[KST].[KST].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[KST].[KST].[KST Gesamt]',
                                                     '_Hierarchy': u'[KST].[KST]'},
                                                    {'Caption': u'All',
                                                     'DisplayInfo': u'1883',
                                                     'LName': u'[Person].[Person].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Person].[Person].[All]',
                                                     '_Hierarchy': u'[Person].[Person]'},
                                                    {'Caption': u'Alle Personen',
                                                     'DisplayInfo': u'178',
                                                     'LName': u'[Person].[Person Austritt].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Person].[Person Austritt].[Alle Personen]',
                                                     '_Hierarchy': u'[Person].[Person Austritt]'},
                                                    {'Caption': u'Alle Personen',
                                                     'DisplayInfo': u'3',
                                                     'LName': u'[Person].[Person aktiv].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Person].[Person aktiv].[Alle Personen]',
                                                     '_Hierarchy': u'[Person].[Person aktiv]'},
                                                    {'Caption': u'Alle Kostenarten',
                                                     'DisplayInfo': u'5',
                                                     'LName': u'[Kostenart].[Kostenart].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Kostenart].[Kostenart].[Alle Kostenarten]',
                                                     '_Hierarchy': u'[Kostenart].[Kostenart]'},
                                                    {'Caption': u'Alle Kostenarten',
                                                     'DisplayInfo': u'40',
                                                     'LName': u'[Kostenart].[Level 02 Bezeichnung].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[Kostenart].[Level 02 Bezeichnung].[Alle Kostenarten]',
                                                     '_Hierarchy': u'[Kostenart].[Level 02 Bezeichnung]'},
                                                    {'Caption': u'All',
                                                     'DisplayInfo': u'2',
                                                     'LName': u'[UserAccount].[UserAccount].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[UserAccount].[UserAccount].[All]',
                                                     '_Hierarchy': u'[UserAccount].[UserAccount]'},
                                                    {'Caption': u'All',
                                                     'DisplayInfo': u'1',
                                                     'LName': u'[UserAccount].[Level 01 username].[(All)]',
                                                     'LNum': u'0',
                                                     'UName': u'[UserAccount].[Level 01 username].[All]',
                                                     '_Hierarchy': u'[UserAccount].[Level 01 username]'}]}},
                    '_name': u'SlicerAxis'}]},
 'CellData': u'',
 'OlapInfo': {'AxesInfo': {'AxisInfo': [{'_name': u'Axis0'},
                                        {'HierarchyInfo': {'Caption': {'_name': u'[Geschlecht].[Geschlecht].[MEMBER_CAPTION]',
                                                                       '_type': u'xsd:string'},
                                                           'DisplayInfo': {'_name': u'[Geschlecht].[Geschlecht].[DISPLAY_INFO]',
                                                                           '_type': u'xsd:unsignedInt'},
                                                           'LName': {'_name': u'[Geschlecht].[Geschlecht].[LEVEL_UNIQUE_NAME]',
                                                                     '_type': u'xsd:string'},
                                                           'LNum': {'_name': u'[Geschlecht].[Geschlecht].[LEVEL_NUMBER]',
                                                                    '_type': u'xsd:int'},
                                                           'UName': {'_name': u'[Geschlecht].[Geschlecht].[MEMBER_UNIQUE_NAME]',
                                                                     '_type': u'xsd:string'},
                                                           '_name': u'[Geschlecht].[Geschlecht]'},
                                         '_name': u'Axis1'},
                                        {'HierarchyInfo': [{'Caption': {'_name': u'[Measures].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Measures].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Measures].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Measures].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Measures].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Measures]'},
                                                           {'Caption': {'_name': u'[Zeit].[Monate].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Zeit].[Monate].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Zeit].[Monate].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Zeit].[Monate].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Zeit].[Monate].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Zeit].[Monate]'},
                                                           {'Caption': {'_name': u'[Zeit].[Zeit].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Zeit].[Zeit].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Zeit].[Zeit].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Zeit].[Zeit].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Zeit].[Zeit].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Zeit].[Zeit]'},
                                                           {'Caption': {'_name': u'[Vertragsbefristung].[Vertragsbefristung].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Vertragsbefristung].[Vertragsbefristung].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Vertragsbefristung].[Vertragsbefristung].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Vertragsbefristung].[Vertragsbefristung].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Vertragsbefristung].[Vertragsbefristung].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Vertragsbefristung].[Vertragsbefristung]'},
                                                           {'Caption': {'_name': u'[Mitarbeitergruppe].[Mitarbeitergruppe].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Mitarbeitergruppe].[Mitarbeitergruppe].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Mitarbeitergruppe].[Mitarbeitergruppe].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Mitarbeitergruppe].[Mitarbeitergruppe].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Mitarbeitergruppe].[Mitarbeitergruppe].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Mitarbeitergruppe].[Mitarbeitergruppe]'},
                                                           {'Caption': {'_name': u'[Funktionsbezeichnung].[Funktionsbezeichnung].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Funktionsbezeichnung].[Funktionsbezeichnung].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Funktionsbezeichnung].[Funktionsbezeichnung].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Funktionsbezeichnung].[Funktionsbezeichnung].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Funktionsbezeichnung].[Funktionsbezeichnung].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Funktionsbezeichnung].[Funktionsbezeichnung]'},
                                                           {'Caption': {'_name': u'[Alter].[Alter].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Alter].[Alter].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Alter].[Alter].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Alter].[Alter].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Alter].[Alter].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Alter].[Alter]'},
                                                           {'Caption': {'_name': u'[Vertragsart].[Vertragsart].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Vertragsart].[Vertragsart].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Vertragsart].[Vertragsart].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Vertragsart].[Vertragsart].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Vertragsart].[Vertragsart].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Vertragsart].[Vertragsart]'},
                                                           {'Caption': {'_name': u'[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Betriebszugeh\xf6rigkeit].[Betriebszugeh\xf6rigkeit]'},
                                                           {'Caption': {'_name': u'[Standort].[Standort].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Standort].[Standort].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Standort].[Standort].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Standort].[Standort].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Standort].[Standort].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Standort].[Standort]'},
                                                           {'Caption': {'_name': u'[Zeitbetrachtung].[Zeitbetrachtung].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Zeitbetrachtung].[Zeitbetrachtung].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Zeitbetrachtung].[Zeitbetrachtung].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Zeitbetrachtung].[Zeitbetrachtung].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Zeitbetrachtung].[Zeitbetrachtung].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Zeitbetrachtung].[Zeitbetrachtung]'},
                                                           {'Caption': {'_name': u'[Kostenstelle].[Kostenstelle].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Kostenstelle].[Kostenstelle].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Kostenstelle].[Kostenstelle].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Kostenstelle].[Kostenstelle].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Kostenstelle].[Kostenstelle].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Kostenstelle].[Kostenstelle]'},
                                                           {'Caption': {'_name': u'[Kostenstelle].[PNR].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Kostenstelle].[PNR].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Kostenstelle].[PNR].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Kostenstelle].[PNR].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Kostenstelle].[PNR].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Kostenstelle].[PNR]'},
                                                           {'Caption': {'_name': u'[Kostenstelle].[Eintritt].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Kostenstelle].[Eintritt].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Kostenstelle].[Eintritt].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Kostenstelle].[Eintritt].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Kostenstelle].[Eintritt].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Kostenstelle].[Eintritt]'},
                                                           {'Caption': {'_name': u'[Kostenstelle].[Eintritt2].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Kostenstelle].[Eintritt2].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Kostenstelle].[Eintritt2].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Kostenstelle].[Eintritt2].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Kostenstelle].[Eintritt2].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Kostenstelle].[Eintritt2]'},
                                                           {'Caption': {'_name': u'[KST].[KST].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[KST].[KST].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[KST].[KST].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[KST].[KST].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[KST].[KST].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[KST].[KST]'},
                                                           {'Caption': {'_name': u'[Person].[Person].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Person].[Person].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Person].[Person].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Person].[Person].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Person].[Person].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Person].[Person]'},
                                                           {'Caption': {'_name': u'[Person].[Person Austritt].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Person].[Person Austritt].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Person].[Person Austritt].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Person].[Person Austritt].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Person].[Person Austritt].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Person].[Person Austritt]'},
                                                           {'Caption': {'_name': u'[Person].[Person aktiv].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Person].[Person aktiv].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Person].[Person aktiv].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Person].[Person aktiv].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Person].[Person aktiv].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Person].[Person aktiv]'},
                                                           {'Caption': {'_name': u'[Kostenart].[Kostenart].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Kostenart].[Kostenart].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Kostenart].[Kostenart].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Kostenart].[Kostenart].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Kostenart].[Kostenart].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Kostenart].[Kostenart]'},
                                                           {'Caption': {'_name': u'[Kostenart].[Level 02 Bezeichnung].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[Kostenart].[Level 02 Bezeichnung].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[Kostenart].[Level 02 Bezeichnung].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[Kostenart].[Level 02 Bezeichnung].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[Kostenart].[Level 02 Bezeichnung].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[Kostenart].[Level 02 Bezeichnung]'},
                                                           {'Caption': {'_name': u'[UserAccount].[UserAccount].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[UserAccount].[UserAccount].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[UserAccount].[UserAccount].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[UserAccount].[UserAccount].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[UserAccount].[UserAccount].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[UserAccount].[UserAccount]'},
                                                           {'Caption': {'_name': u'[UserAccount].[Level 01 username].[MEMBER_CAPTION]',
                                                                        '_type': u'xsd:string'},
                                                            'DisplayInfo': {'_name': u'[UserAccount].[Level 01 username].[DISPLAY_INFO]',
                                                                            '_type': u'xsd:unsignedInt'},
                                                            'LName': {'_name': u'[UserAccount].[Level 01 username].[LEVEL_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            'LNum': {'_name': u'[UserAccount].[Level 01 username].[LEVEL_NUMBER]',
                                                                     '_type': u'xsd:int'},
                                                            'UName': {'_name': u'[UserAccount].[Level 01 username].[MEMBER_UNIQUE_NAME]',
                                                                      '_type': u'xsd:string'},
                                                            '_name': u'[UserAccount].[Level 01 username]'}],
                                         '_name': u'SlicerAxis'}]},
              'CellInfo': {'CellOrdinal': {'_name': u'CELL_ORDINAL',
                                           '_type': u'xsd:unsignedInt'},
                           'FmtValue': {'_name': u'FORMATTED_VALUE',
                                        '_type': u'xsd:string'},
                           'Value': {'_name': u'VALUE'}},
              'CubeInfo': {'Cube': {'CubeName': u'fused',
                                    'LastDataUpdate': u'2012-11-16T07:47:31.283333',
                                    'LastSchemaUpdate': u'2012-11-16T07:47:28.106667'}}},
 'schema': {'_elementFormDefault': u'qualified',
            '_targetNamespace': u'urn:schemas-microsoft-com:xml-analysis:mddataset',
            'complexType': [{'_name': u'MemberType',
                             'attribute': {'_name': u'Hierarchy',
                                           '_type': u'xs:string'},
                             'sequence': {'any': {'_maxOccurs': u'unbounded',
                                                  '_minOccurs': u'0',
                                                  '_namespace': u'##targetNamespace',
                                                  '_processContents': u'skip'}}},
                            {'_name': u'PropType',
                             'attribute': [{'_name': u'name',
                                            '_type': u'xs:string',
                                            '_use': u'required'},
                                           {'_name': u'type',
                                            '_type': u'xs:QName'}],
                             'sequence': {'element': {'_minOccurs': u'0',
                                                      '_name': u'Default'}}},
                            {'_name': u'TupleType',
                             'sequence': {'element': {'_maxOccurs': u'unbounded',
                                                      '_minOccurs': u'0',
                                                      '_name': u'Member',
                                                      '_type': u'MemberType'}}},
                            {'_name': u'MembersType',
                             'attribute': {'_name': u'Hierarchy',
                                           '_type': u'xs:string',
                                           '_use': u'required'},
                             'sequence': {'element': {'_maxOccurs': u'unbounded',
                                                      '_minOccurs': u'0',
                                                      '_name': u'Member',
                                                      '_type': u'MemberType'}}},
                            {'_name': u'TuplesType',
                             'sequence': {'element': {'_maxOccurs': u'unbounded',
                                                      '_minOccurs': u'0',
                                                      '_name': u'Tuple',
                                                      '_type': u'TupleType'}}},
                            {'_name': u'SetListType',
                             'attribute': {'_name': u'Size',
                                           '_type': u'xs:unsignedInt'},
                             'group': {'_maxOccurs': u'unbounded',
                                       '_minOccurs': u'0',
                                       '_ref': u'SetType'}},
                            {'_name': u'OlapInfo',
                             'sequence': {'element': [{'_name': u'CubeInfo',
                                                       'complexType': {'sequence': {'element': {'_maxOccurs': u'unbounded',
                                                                                                '_name': u'Cube',
                                                                                                'complexType': {'sequence': {'element': [{'_name': u'CubeName',
                                                                                                                                          '_type': u'xs:string'},
                                                                                                                                         {'_minOccurs': u'0',
                                                                                                                                          '_name': u'LastDataUpdate',
                                                                                                                                          '_type': u'xs:dateTime'},
                                                                                                                                         {'_minOccurs': u'0',
                                                                                                                                          '_name': u'LastSchemaUpdate',
                                                                                                                                          '_type': u'xs:dateTime'}]}}}}}},
                                                      {'_name': u'AxesInfo',
                                                       'complexType': {'sequence': {'element': {'_maxOccurs': u'unbounded',
                                                                                                '_name': u'AxisInfo',
                                                                                                'complexType': {'attribute': {'_name': u'name',
                                                                                                                              '_type': u'xs:string'},
                                                                                                                'sequence': {'element': {'_maxOccurs': u'unbounded',
                                                                                                                                         '_minOccurs': u'0',
                                                                                                                                         '_name': u'HierarchyInfo',
                                                                                                                                         'complexType': {'attribute': {'_name': u'name',
                                                                                                                                                                       '_type': u'xs:string',
                                                                                                                                                                       '_use': u'required'},
                                                                                                                                                         'sequence': {'any': {'_maxOccurs': u'unbounded',
                                                                                                                                                                              '_minOccurs': u'0',
                                                                                                                                                                              '_namespace': u'##targetNamespace',
                                                                                                                                                                              '_processContents': u'skip'}}}}}}}}}},
                                                      {'_name': u'CellInfo',
                                                       'complexType': {'choice': {'_maxOccurs': u'unbounded',
                                                                                  '_minOccurs': u'0',
                                                                                  'any': {'_maxOccurs': u'unbounded',
                                                                                          '_minOccurs': u'0',
                                                                                          '_namespace': u'##targetNamespace',
                                                                                          '_processContents': u'skip'}}}}]}},
                            {'_name': u'Axes',
                             'sequence': {'element': {'_maxOccurs': u'unbounded',
                                                      '_name': u'Axis',
                                                      'complexType': {'attribute': {'_name': u'name',
                                                                                    '_type': u'xs:string'},
                                                                      'group': {'_maxOccurs': u'unbounded',
                                                                                '_minOccurs': u'0',
                                                                                '_ref': u'SetType'}}}}},
                            {'_name': u'CellData',
                             'sequence': {'element': {'_maxOccurs': u'unbounded',
                                                      '_minOccurs': u'0',
                                                      '_name': u'Cell',
                                                      'complexType': {'attribute': {'_name': u'CellOrdinal',
                                                                                    '_type': u'xs:unsignedInt',
                                                                                    '_use': u'required'},
                                                                      'sequence': {'any': {'_maxOccurs': u'unbounded',
                                                                                           '_minOccurs': u'0',
                                                                                           '_namespace': u'##targetNamespace',
                                                                                           '_processContents': u'skip'}}}}}}],
            'element': {'_name': u'root',
                        'complexType': {'sequence': {'any': {'_minOccurs': u'0',
                                                             '_namespace': u'http://www.w3.org/2001/XMLSchema',
                                                             '_processContents': u'strict'},
                                                     'element': [{'_minOccurs': u'0',
                                                                  '_name': u'OlapInfo',
                                                                  '_type': u'OlapInfo'},
                                                                 {'_minOccurs': u'0',
                                                                  '_name': u'Axes',
                                                                  '_type': u'Axes'},
                                                                 {'_minOccurs': u'0',
                                                                  '_name': u'CellData',
                                                                  '_type': u'CellData'}]}}},
            'group': {'_name': u'SetType',
                      'choice': {'element': [{'_name': u'Members',
                                              '_type': u'MembersType'},
                                             {'_name': u'Tuples',
                                              '_type': u'TuplesType'},
                                             {'_name': u'CrossProduct',
                                              '_type': u'SetListType'},
                                             {'_ref': u'msxmla:NormTupleSet'},
                                             {'_name': u'Union',
                                              'complexType': {'group': {'_maxOccurs': u'unbounded',
                                                                        '_minOccurs': u'0',
                                                                        '_ref': u'SetType'}}}]}},
            'import': {'_namespace': u'http://schemas.microsoft.com/analysisservices/2003/xmla'}}}
