"""
select [Gender].[Gender].ALLMEMBERS on columns from [Sales]

"""

result={'Axes': {'Axis': [{'Tuples': {'Tuple': [{'Member': {'Caption': 'F',
                                                     'DisplayInfo': '0',
                                                     'LName': '[Gender].[Gender]',
                                                     'LNum': '1',
                                                     'UName': '[Gender].[F]',
                                                     '_Hierarchy': 'Gender'}},
                                         {'Member': {'Caption': 'M',
                                                     'DisplayInfo': '131072',
                                                     'LName': '[Gender].[Gender]',
                                                     'LNum': '1',
                                                     'UName': '[Gender].[M]',
                                                     '_Hierarchy': 'Gender'}}]},
                    '_name': 'Axis0'},
                   {'Tuples': {'Tuple': None}, '_name': 'SlicerAxis'}]},
 'CellData': {'Cell': [{'FmtValue': '131.558',
                        'FormatString': 'Standard',
                        'Value': 131558.0,
                        '_CellOrdinal': '0'},
                       {'FmtValue': '135.215',
                        'FormatString': 'Standard',
                        'Value': 135215.0,
                        '_CellOrdinal': '1'}]},
 'OlapInfo': {'AxesInfo': {'AxisInfo': [{'HierarchyInfo': {'Caption': {'_name': '[Gender].[MEMBER_CAPTION]'},
                                                           'DisplayInfo': {'_name': '[Gender].[DISPLAY_INFO]'},
                                                           'LName': {'_name': '[Gender].[LEVEL_UNIQUE_NAME]'},
                                                           'LNum': {'_name': '[Gender].[LEVEL_NUMBER]'},
                                                           'UName': {'_name': '[Gender].[MEMBER_UNIQUE_NAME]'},
                                                           '_name': 'Gender'},
                                         '_name': 'Axis0'},
                                        {'_name': 'SlicerAxis'}]},
              'CellInfo': {'FmtValue': {'_name': 'FORMATTED_VALUE'},
                           'FormatString': {'_name': 'FORMAT_STRING'},
                           'Value': {'_name': 'VALUE'}},
              'CubeInfo': {'Cube': {'CubeName': 'Sales'}}}}
